name: Release

on:
  push:
    tags:
      - 'v*' # Triggers on tags like v1.0, v2.3.4, etc.
  workflow_dispatch:

permissions:
  contents: write # Required to create the release and upload assets

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Build Binaries
        id: build
        run: |
          APP_NAME="timeline"
          PACKAGE_PATH="./cmd/"
          # Create a directory to hold the artifacts
          mkdir -p dist

          echo "Building for Windows (amd64)..."
          GOOS=windows GOARCH=amd64 go build -v -o dist/${APP_NAME}-windows-amd64.exe $PACKAGE_PATH

          echo "Building for macOS (Intel amd64)..."
          GOOS=darwin GOARCH=amd64 go build -v -o dist/${APP_NAME}-darwin-amd64 $PACKAGE_PATH

          echo "Building for macOS (Apple Silicon arm64)..."
          GOOS=darwin GOARCH=arm64 go build -v -o dist/${APP_NAME}-darwin-arm64 $PACKAGE_PATH

          # List files to verify
          ls -l dist/

      # - name: Upload Artifacts
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     tag: ${{ github.ref }}
      #     file: ./dist/*
      #     file_glob: true

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*
          generate_release_notes: true
          make_latest: true
          token: ${{ secrets.GITHUB_TOKEN }}
          # token: ${{ secrets.GH_PAT_FOR_RELEASES }}
